### ISSUE TITLE
add option to ctest

### ISSUE THREAD

**Issue by grimgort** [SGauvin/ctest-telescope.nvim#1]
Hello,

it should be possible to add arguments to ctest because with multi-configuration compilers we have to add the -C debug option to find the tests.
test --test-dir <build_folder> --show-only=json-v1 -C  Debug

**Comment by SGauvin** [comment]
Hi @grimgort,
Thank you for the issue!
Could you please checkout this pull request and let me know if it works for you? https://github.com/SGauvin/ctest-telescope.nvim/pull/2

If you are using `lazy.nvim`, you can add `branch="extra_args",` in the entry.

**Comment by SGauvin** [comment]
Forgot to mention that to set arguments, you need to use the `extra_ctest_args` option like so
```lua
require("ctest-telescope").setup({
  dap_config = { ... },
  extra_ctest_args = { "-C", "Debug" },
})
```

**Comment by grimgort** [comment]
That doesn't seem to be working either,
![image](https://github.com/user-attachments/assets/9215e728-e526-4532-9c57-621e8df7862a)
![image](https://github.com/user-attachments/assets/b78d2aaf-0408-4caf-80fb-c4c3db8d7c11)
![image](https://github.com/user-attachments/assets/62035b1a-0319-436c-a38b-7fd5858b1467)
![image](https://github.com/user-attachments/assets/9d67e721-1702-481f-a356-4c63fe2f6dff)

**Comment by SGauvin** [comment]
@grimgort Mmmmh weird.
Could you give me the ouput of both `ctest --test-dir <build_folder> --show-only=json-v1 -C Debug` and `ctest --test-dir <build_folder> --show-only=json-v1`?

Also I can see that your are on Windows, I don't know if this could have anything to do with it. Are you on WSL?

**Comment by grimgort** [comment]
it s working with this fix

https://github.com/SGauvin/ctest-telescope.nvim/pull/2/files#r1744995856

**Comment by SGauvin** [comment]
@grimgort Awesome, thanks for spotting that silly mistake (I wish Lua had strong typing...)
I'll merge the change most likely this evening (eastern time).

FYI in case you didn't know, you don't need to define both `opts` and also make a call to `setup` in case you didn't know.
https://lazy.folke.io/spec#spec-setup

I hope you'll find the plugin useful :)

**Comment by SGauvin** [comment]
@grimgort sorry for the delay, was busy during the last couple of days. I just merged this, please feel free to reach out again if you have any issues, and thanks for the report :)
